 # Конфигурация приложения
password: "123456"  # Замените на свой пароль

# Настройки сервера
server:
  host: "0.0.0.0"
  port: 8501

# Пути к данным
data_path: "/data"  # Замените на путь к вашим данным