version: '3'

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data  # Монтируем директорию с данными
      - ./config.yaml:/app/config.yaml  # Монтируем конфигурацию
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1 